### ISSUE TITLE
Browser Callbacks not being handled

### ISSUE THREAD

**Issue by real-limitless** [cornips/flobro#54] opened 2019-11-28 22:41 UTC
**Describe the bug**
A clear and concise description of what the bug is
The Program does not handle browser Javascripts call backs adequately to handle 3rd party sites authorization.

EXAMPLE CODE that is failing.. 
if (window.opener) window.opener.postMessage('LOGIN_COMPLETE', '*');
else if (window.parent) window.parent.postMessage('LOGIN_COMPLETE', '*');

Flobro opens new authuntication tabs in main chrome browser however after login in successfully the Window.opener.postMessage fails to "PostMessage" to window inside Flobro.

**Steps to reproduce**
Open Flobro...
Goto Settings, Enter https://foxnews.com as URL
have Flobro open web page.
click Live(in fox news)
Click a 3rd party subscription service (Spectrum, Xfinity... etc)...
After clicking a 3rd party
the site opens two pop ups.
After logging successfully, it fails to update in the main browser windows.

**Expected behavior**
After successful login to a 3rd party login it should refresh on the main site.

**Screenshots**

**Environment variables:**
 - OS: Windows
 - Version: e.g. 0.2.1
 - Chrome version: Latest

**Additional context**
Spectrum is the 3rd party service.

**Comment by cornips** [comment] 2020-08-12 14:13
Related to #40

**Comment by cornips** [comment] 2020-08-12 14:23
Duplicate of #40

**Closed as completed by cornips** 2020-08-12 14:23 UTC
Labels: Duplicate
