### ISSUE TITLE
Turn App Into Self-Contained Executable File

### ISSUE THREAD

**Issue by Exper1mental** [cornips/flobro#16] opened 2018-10-26 20:54 UTC
Personally I think this app is one of the best kept secrets of the Google Chrome extension store. I thought it would be really awesome if this could become a completely stand-alone application. As someone who has actively used rainmeter I see this being a powerful tool to compliment my on-desktop information center.

As it is there's not really a good way (or any way) to display borderless web pages on the desktop. For desktop customizers like me, a stand-alone app like this would be a game changer and allow us to easier display web content as part of our desktops.

Might not be practical, but I thought I'd toss it out there in case it was.

**Comment by cornips** [comment] 2018-10-29 10:20
Duplicate of #6

**Closed as completed** 2018-10-29 10:21 UTC
Labels: Duplicate
