### ISSUE TITLE
Flobro no longer 'always on top'

### ISSUE THREAD

**Issue by andrewjjolly** [cornips/flobro#50] opened 2019-10-01 13:43 UTC
**Describe the bug**

Flobro used to work fine, but it is no longer 'staying on top' - making it like any other window pretty much. See below for what I did.

I have tried restarting computer, uninstalling and reinstalling app, changing page that it points to - issue persists.
 
**Steps to reproduce**

Open flobro in apps
open pomodone.app as the website (my default)
resize window
maximised window to full screen
resized again.
It is no longer full screen

**Expected behavior**

I expect the flobro window to remain always on top at all times.

**Screenshots**

**Environment variables:**
 - OS: e.g. Windows 10 Enterprise, Version 1903, OS Build 18362.356
 - Version: e.g. 0.2.2
 - Chrome version: 77.0.3865.90 (Official Build) (32-bit)

**Additional context**

**Comment by tomByrer** [comment] 2019-10-03 00:59
Old bug
https://github.com/cornips/flobro/issues/30

**Comment by andrewjjolly** [comment] 2019-10-03 14:52
Thanks,

I didn't know it was an old bug - is there something I should do to get
around it?

**Comment by MrMdR** [comment] 2019-10-27 13:53
Hello, I have the same problem. Window won't stay on top of other windows or tabs. 
This kinda makes the plugin useless, sadly :( <3

**Comment by raiddto** [comment] 2019-11-13 23:39
Same here. It was working last time I was using it Nov 12

**Comment by mikeaustin** [comment] 2020-04-11 22:10
I just installed the Chrome app, and unfortunately, it doesn't stay on top, which was the purpose of the app I thought?

**Comment by cornips** [comment] 2020-04-12 14:58
Any Mac users experiencing this bug? Seems like a Windows bug, and I can't reproduce. Maybe it has to do with Google ending Chrome App support for non-Chrome OS.

**Comment by andrewjjolly** [comment] 2020-04-12 15:52
It was windows only for me - but I'm back working where they will let me
install deskpins again so its all good. Thanks.

**Comment by metrolander** [comment] 2020-04-20 20:10
I think it may be important to note that when this breaks, the normal Chrome window becomes always on top instead of flobro. Not sure how to reset it either

**Comment by cornips** [comment] 2020-08-04 20:13
Seems like more people experiencing this issue. Still investigating this.
Closing duplicate of #30

**Closed as completed by cornips** 2020-08-04 20:13 UTC
Labels: Bug
