### ISSUE TITLE
Flobro is failing to stay on top

### ISSUE THREAD

**Issue by Shaurya2003** [cornips/flobro#63] opened 2020-05-07 14:29 UTC
I used Flobro a lot of times.
But today it suddenly failed to say on top of other screens

This was caused after searching www.google.com

I really loved this app, plz help

**Comment by cornips** [comment] 2020-08-04 20:07
I'm sorry to hear that. Seems like more people experiencing this issue. Still investigating this.
Closing because duplicate of #30

**Closed as completed by cornips** 2020-08-04 20:07 UTC
