### ISSUE TITLE
Enable microphone and camera

### ISSUE THREAD

**Issue by aranedam2** [cornips/flobro#69] opened 2020-08-29 17:24 UTC
Hello,

I'm trying to use this with Google Meet. I'm a teacher and I need to see my computer screen as well as my students on Google Meet at the same time. This floating tab app is perfect, except that I can't enable my microphone and camera so that my remote students can see me. Can you help with me asap, please!!

Thank you very very much!
-Belen

**Comment by cornips** [comment] 2020-08-30 10:08
Thank you for sharing your use case!

Due to many complaints about privacy the microphone and webcam permission was removed in version 0.2.2

I will rethink this use case in the new stand-alone rebuild in #6

**Comment by cornips** [comment] 2020-08-30 22:01
Duplicate of #56

**Closed as completed by cornips** 2020-08-30 22:01 UTC
Labels: Enhancement

**Comment by czechtech** [comment] 2020-09-12 19:14
I second @aranedam2 's request.  I'm a teacher, and am looking for camera access.  However, I understand @cornips 's concern about privacy.

I see the commit that removed the permission for camera/audio: [61aba87](https://github.com/flobro/flobro-chrome-app/commit/61aba87a3e3673020c47595dff9fbd013a7a9875)

Could camera access be added as an option, off by default?  Can a manifest.json file be dynamic?

**Comment by cornips** [comment] 2020-09-15 00:23
Unfortunately, Chrome needs the permissions on beforehand so there isn't a dynamic solution.
I will investigate options for the stand alone app rebuild in #6.

**Comment by czechtech** [comment] 2020-09-15 15:09
There must be more than just including audioCapture and videoCapture in the manifest.json.  I installed several older versions of FloBro (0.2.1, 0.2.0, 0.1.2) and testing a live camera on FloBro by visiting this website showed nothing:
   https://www.kirupa.com/html5/accessing_your_webcam_in_html5.htm

In Chrome, permissions must be confirmed by clicking on a popup, but a popup never happens in FloBro.
