### ISSUE TITLE
Floating Browser Window no longer stays on top

### ISSUE THREAD

**Issue by cd419** [cornips/flobro#30] opened 2019-05-10 20:45 UTC
**Describe the bug**
The floating browser window no longer stays on top of other windows on Windows 10

**Steps to reproduce**
1. Launch Floating Browser Window
2. Page loads and I start a video playing on youtube TV
3. Click away from the Floating Browser Window to another application
4. Floating browser window goes behind the new active application (Chrome, Outlook, ETC.) 

**Expected behavior**
I expected the window to stay on top of all other active windows

**Screenshots**

**Please complete the following information:**
 - OS: Windows 10 Pro
 - Version 0.1.2 beta
-Chrome version 74.0.3729.131

**Comment by cornips** [comment] 2019-07-20 23:28
Does this issue still occur to you after the recent update (version 0.2.1)?

**Comment by cd419** [comment] 2019-07-29 20:25
I just updated to 0.2.1 on chrome  Version 75.0.3770.142 (Official Build)
(32-bit) and I'm still seeing the issue.

**Comment by raiddto** [comment] 2019-11-21 00:13
I'm experiencing this bug til this day since Nov 12, 2019

**Comment by cornips** [comment] 2020-09-03 21:40
I'm not able to reproduce this bug. Will close this issue for that reason.

If someone is still experiencing this behaviour in 0.2.4+, please open a new bug report.

**Closed as completed by cornips** 2020-09-03 21:40 UTC
Labels: Bug, Vague
