### ISSUE TITLE
Control for toggle the "always on top" state

### ISSUE THREAD

**Issue by richardbdzoch** [cornips/flobro#65] opened 2020-06-17 22:04 UTC
Hi. Sorry I dont use github much so I dont know the habits. I miss the control for toggle the always on top state. You should add it to panel controls. I have "reused" the pin control for this purpose (I wasnt using the pin control)

See here https://github.com/richardbdzoch/Flobro/commit/faf7f2c7df739b6aaf7c9cfc204f2cc57f53f023

**Comment by cornips** [comment] 2020-08-12 13:49
I think the option to 'pin' the title bar is not clear to users anyway. People expect to toggle the always-on-top setting with this, so thanks for your addition. I created PR #68 for your modification.

**Comment by cornips** [comment] 2020-08-12 13:52
Duplicate of #15

**Closed as completed by cornips** 2020-08-12 13:52 UTC
Labels: Enhancement
